---

- name: Install Nginx
  apt: name=nginx state=installed

- name: Create the Nginx configuration file
  template: src=site.conf.j2 dest=/etc/nginx/sites-available/{{ project_name }}.conf

- name: Ensure that the default site is removed
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ project_name }}.conf dest=/etc/nginx/sites-enabled/{{ project_name }}.conf state=link
  notify: Reload Nginx

- name: Ensure Nginx service is started, enable service on restart
  service: name=nginx state=restarted enabled=yes
